package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TClientInfo generated by hbm2java
 */
@Entity
@Table(name = "T_CLIENT_INFO")
public class TClientInfo implements java.io.Serializable {

	private String clientId;
	private String clientType;
	private String clientName;
	private String identifiedType;
	private String identifiedNo;
	private String investerId;

	public TClientInfo() {
	}

	public TClientInfo(String clientId) {
		this.clientId = clientId;
	}

	public TClientInfo(String clientId, String clientType, String clientName, String identifiedType,
			String identifiedNo, String investerId) {
		this.clientId = clientId;
		this.clientType = clientType;
		this.clientName = clientName;
		this.identifiedType = identifiedType;
		this.identifiedNo = identifiedNo;
		this.investerId = investerId;
	}

	@Id

	@Column(name = "CLIENT_ID", unique = true, nullable = false, length = 20)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "CLIENT_TYPE", length = 1)
	public String getClientType() {
		return this.clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	@Column(name = "CLIENT_NAME", length = 100)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "IDENTIFIED_TYPE", length = 1)
	public String getIdentifiedType() {
		return this.identifiedType;
	}

	public void setIdentifiedType(String identifiedType) {
		this.identifiedType = identifiedType;
	}

	@Column(name = "IDENTIFIED_NO", length = 100)
	public String getIdentifiedNo() {
		return this.identifiedNo;
	}

	public void setIdentifiedNo(String identifiedNo) {
		this.identifiedNo = identifiedNo;
	}

	@Column(name = "INVESTER_ID", length = 20)
	public String getInvesterId() {
		return this.investerId;
	}

	public void setInvesterId(String investerId) {
		this.investerId = investerId;
	}

}
