package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCurrFundBalance generated by hbm2java
 */
@Entity
@Table(name = "T_CURR_FUND_BALANCE")
public class TCurrFundBalance implements java.io.Serializable {

	private String accountId;
	private BigDecimal totalMoney;
	private BigDecimal prebalance;
	private BigDecimal deposit;
	private BigDecimal withdraw;
	private BigDecimal margin;
	private BigDecimal canUseMoney;
	private BigDecimal canWithdrawMoney;
	private BigDecimal frozenMoney;
	private BigDecimal fee;
	private BigDecimal frozenPremium;
	private BigDecimal frozenFee;
	private BigDecimal todayProfit;
	private BigDecimal totalProfit;

	public TCurrFundBalance() {
	}

	public TCurrFundBalance(String accountId) {
		this.accountId = accountId;
	}

	public TCurrFundBalance(String accountId, BigDecimal totalMoney, BigDecimal prebalance, BigDecimal deposit,
			BigDecimal withdraw, BigDecimal margin, BigDecimal canUseMoney, BigDecimal canWithdrawMoney,
			BigDecimal frozenMoney, BigDecimal fee, BigDecimal frozenPremium, BigDecimal frozenFee,
			BigDecimal todayProfit, BigDecimal totalProfit) {
		this.accountId = accountId;
		this.totalMoney = totalMoney;
		this.prebalance = prebalance;
		this.deposit = deposit;
		this.withdraw = withdraw;
		this.margin = margin;
		this.canUseMoney = canUseMoney;
		this.canWithdrawMoney = canWithdrawMoney;
		this.frozenMoney = frozenMoney;
		this.fee = fee;
		this.frozenPremium = frozenPremium;
		this.frozenFee = frozenFee;
		this.todayProfit = todayProfit;
		this.totalProfit = totalProfit;
	}

	@Id

	@Column(name = "ACCOUNT_ID", unique = true, nullable = false, length = 20)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "TOTAL_MONEY", scale = 3)
	public BigDecimal getTotalMoney() {
		return this.totalMoney;
	}

	public void setTotalMoney(BigDecimal totalMoney) {
		this.totalMoney = totalMoney;
	}

	@Column(name = "PREBALANCE", scale = 3)
	public BigDecimal getPrebalance() {
		return this.prebalance;
	}

	public void setPrebalance(BigDecimal prebalance) {
		this.prebalance = prebalance;
	}

	@Column(name = "DEPOSIT", scale = 3)
	public BigDecimal getDeposit() {
		return this.deposit;
	}

	public void setDeposit(BigDecimal deposit) {
		this.deposit = deposit;
	}

	@Column(name = "WITHDRAW", scale = 3)
	public BigDecimal getWithdraw() {
		return this.withdraw;
	}

	public void setWithdraw(BigDecimal withdraw) {
		this.withdraw = withdraw;
	}

	@Column(name = "MARGIN", scale = 3)
	public BigDecimal getMargin() {
		return this.margin;
	}

	public void setMargin(BigDecimal margin) {
		this.margin = margin;
	}

	@Column(name = "CAN_USE_MONEY", scale = 3)
	public BigDecimal getCanUseMoney() {
		return this.canUseMoney;
	}

	public void setCanUseMoney(BigDecimal canUseMoney) {
		this.canUseMoney = canUseMoney;
	}

	@Column(name = "CAN_WITHDRAW_MONEY", scale = 3)
	public BigDecimal getCanWithdrawMoney() {
		return this.canWithdrawMoney;
	}

	public void setCanWithdrawMoney(BigDecimal canWithdrawMoney) {
		this.canWithdrawMoney = canWithdrawMoney;
	}

	@Column(name = "FROZEN_MONEY", scale = 3)
	public BigDecimal getFrozenMoney() {
		return this.frozenMoney;
	}

	public void setFrozenMoney(BigDecimal frozenMoney) {
		this.frozenMoney = frozenMoney;
	}

	@Column(name = "FEE", scale = 3)
	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	@Column(name = "FROZEN_PREMIUM", scale = 3)
	public BigDecimal getFrozenPremium() {
		return this.frozenPremium;
	}

	public void setFrozenPremium(BigDecimal frozenPremium) {
		this.frozenPremium = frozenPremium;
	}

	@Column(name = "FROZEN_FEE", scale = 3)
	public BigDecimal getFrozenFee() {
		return this.frozenFee;
	}

	public void setFrozenFee(BigDecimal frozenFee) {
		this.frozenFee = frozenFee;
	}

	@Column(name = "TODAY_PROFIT", scale = 3)
	public BigDecimal getTodayProfit() {
		return this.todayProfit;
	}

	public void setTodayProfit(BigDecimal todayProfit) {
		this.todayProfit = todayProfit;
	}

	@Column(name = "TOTAL_PROFIT", scale = 3)
	public BigDecimal getTotalProfit() {
		return this.totalProfit;
	}

	public void setTotalProfit(BigDecimal totalProfit) {
		this.totalProfit = totalProfit;
	}

}
