package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCurrPortfolioBalance generated by hbm2java
 */
@Entity
@Table(name = "T_CURR_PORTFOLIO_BALANCE")
public class TCurrPortfolioBalance implements java.io.Serializable {

	private String portfolioId;
	private String userId;
	private BigDecimal limitMoney;
	private BigDecimal preLimitMoney;
	private BigDecimal margin;
	private BigDecimal canUseMoney;
	private BigDecimal frozenMoney;
	private BigDecimal fee;
	private BigDecimal frozenPremium;
	private BigDecimal frozenFee;
	private BigDecimal todayProfit;
	private BigDecimal totalProfit;

	public TCurrPortfolioBalance() {
	}

	public TCurrPortfolioBalance(String portfolioId, String userId) {
		this.portfolioId = portfolioId;
		this.userId = userId;
	}

	public TCurrPortfolioBalance(String portfolioId, String userId, BigDecimal limitMoney, BigDecimal preLimitMoney,
			BigDecimal margin, BigDecimal canUseMoney, BigDecimal frozenMoney, BigDecimal fee, BigDecimal frozenPremium,
			BigDecimal frozenFee, BigDecimal todayProfit, BigDecimal totalProfit) {
		this.portfolioId = portfolioId;
		this.userId = userId;
		this.limitMoney = limitMoney;
		this.preLimitMoney = preLimitMoney;
		this.margin = margin;
		this.canUseMoney = canUseMoney;
		this.frozenMoney = frozenMoney;
		this.fee = fee;
		this.frozenPremium = frozenPremium;
		this.frozenFee = frozenFee;
		this.todayProfit = todayProfit;
		this.totalProfit = totalProfit;
	}

	@Id

	@Column(name = "PORTFOLIO_ID", unique = true, nullable = false, length = 12)
	public String getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(String portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "LIMIT_MONEY", scale = 3)
	public BigDecimal getLimitMoney() {
		return this.limitMoney;
	}

	public void setLimitMoney(BigDecimal limitMoney) {
		this.limitMoney = limitMoney;
	}

	@Column(name = "PRE_LIMIT_MONEY", scale = 3)
	public BigDecimal getPreLimitMoney() {
		return this.preLimitMoney;
	}

	public void setPreLimitMoney(BigDecimal preLimitMoney) {
		this.preLimitMoney = preLimitMoney;
	}

	@Column(name = "MARGIN", scale = 3)
	public BigDecimal getMargin() {
		return this.margin;
	}

	public void setMargin(BigDecimal margin) {
		this.margin = margin;
	}

	@Column(name = "CAN_USE_MONEY", scale = 3)
	public BigDecimal getCanUseMoney() {
		return this.canUseMoney;
	}

	public void setCanUseMoney(BigDecimal canUseMoney) {
		this.canUseMoney = canUseMoney;
	}

	@Column(name = "FROZEN_MONEY", scale = 3)
	public BigDecimal getFrozenMoney() {
		return this.frozenMoney;
	}

	public void setFrozenMoney(BigDecimal frozenMoney) {
		this.frozenMoney = frozenMoney;
	}

	@Column(name = "FEE", scale = 3)
	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	@Column(name = "FROZEN_PREMIUM", scale = 3)
	public BigDecimal getFrozenPremium() {
		return this.frozenPremium;
	}

	public void setFrozenPremium(BigDecimal frozenPremium) {
		this.frozenPremium = frozenPremium;
	}

	@Column(name = "FROZEN_FEE", scale = 3)
	public BigDecimal getFrozenFee() {
		return this.frozenFee;
	}

	public void setFrozenFee(BigDecimal frozenFee) {
		this.frozenFee = frozenFee;
	}

	@Column(name = "TODAY_PROFIT", scale = 3)
	public BigDecimal getTodayProfit() {
		return this.todayProfit;
	}

	public void setTodayProfit(BigDecimal todayProfit) {
		this.todayProfit = todayProfit;
	}

	@Column(name = "TOTAL_PROFIT", scale = 3)
	public BigDecimal getTotalProfit() {
		return this.totalProfit;
	}

	public void setTotalProfit(BigDecimal totalProfit) {
		this.totalProfit = totalProfit;
	}

}
