package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TCurrPortfolioPosition generated by hbm2java
 */
@Entity
@Table(name = "T_CURR_PORTFOLIO_POSITION")
public class TCurrPortfolioPosition implements java.io.Serializable {

	private TCurrPortfolioPositionId id;
	private String userId;
	private String exchClientId;
	private String productId;
	private Long position;
	private Long frozenPosition;
	private BigDecimal margin;
	private BigDecimal realMargin;
	private BigDecimal positionCost;
	private BigDecimal premium;
	private Long todayOpen;
	private BigDecimal todayProfit;
	private BigDecimal totalProfit;

	public TCurrPortfolioPosition() {
	}

	public TCurrPortfolioPosition(TCurrPortfolioPositionId id, String userId, String exchClientId, String productId) {
		this.id = id;
		this.userId = userId;
		this.exchClientId = exchClientId;
		this.productId = productId;
	}

	public TCurrPortfolioPosition(TCurrPortfolioPositionId id, String userId, String exchClientId, String productId,
			Long position, Long frozenPosition, BigDecimal margin, BigDecimal realMargin, BigDecimal positionCost,
			BigDecimal premium, Long todayOpen, BigDecimal todayProfit, BigDecimal totalProfit) {
		this.id = id;
		this.userId = userId;
		this.exchClientId = exchClientId;
		this.productId = productId;
		this.position = position;
		this.frozenPosition = frozenPosition;
		this.margin = margin;
		this.realMargin = realMargin;
		this.positionCost = positionCost;
		this.premium = premium;
		this.todayOpen = todayOpen;
		this.todayProfit = todayProfit;
		this.totalProfit = totalProfit;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "portfolioId", column = @Column(name = "PORTFOLIO_ID", nullable = false, length = 12)),
			@AttributeOverride(name = "instrumentId", column = @Column(name = "INSTRUMENT_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "hedgeFlag", column = @Column(name = "HEDGE_FLAG", nullable = false, length = 1)),
			@AttributeOverride(name = "direction", column = @Column(name = "DIRECTION", nullable = false, length = 50)) })
	public TCurrPortfolioPositionId getId() {
		return this.id;
	}

	public void setId(TCurrPortfolioPositionId id) {
		this.id = id;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "EXCH_CLIENT_ID", nullable = false, length = 20)
	public String getExchClientId() {
		return this.exchClientId;
	}

	public void setExchClientId(String exchClientId) {
		this.exchClientId = exchClientId;
	}

	@Column(name = "PRODUCT_ID", nullable = false, length = 30)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "POSITION", precision = 13, scale = 0)
	public Long getPosition() {
		return this.position;
	}

	public void setPosition(Long position) {
		this.position = position;
	}

	@Column(name = "FROZEN_POSITION", precision = 13, scale = 0)
	public Long getFrozenPosition() {
		return this.frozenPosition;
	}

	public void setFrozenPosition(Long frozenPosition) {
		this.frozenPosition = frozenPosition;
	}

	@Column(name = "MARGIN", scale = 3)
	public BigDecimal getMargin() {
		return this.margin;
	}

	public void setMargin(BigDecimal margin) {
		this.margin = margin;
	}

	@Column(name = "REAL_MARGIN", scale = 3)
	public BigDecimal getRealMargin() {
		return this.realMargin;
	}

	public void setRealMargin(BigDecimal realMargin) {
		this.realMargin = realMargin;
	}

	@Column(name = "POSITION_COST", scale = 3)
	public BigDecimal getPositionCost() {
		return this.positionCost;
	}

	public void setPositionCost(BigDecimal positionCost) {
		this.positionCost = positionCost;
	}

	@Column(name = "PREMIUM", scale = 3)
	public BigDecimal getPremium() {
		return this.premium;
	}

	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}

	@Column(name = "TODAY_OPEN", precision = 13, scale = 0)
	public Long getTodayOpen() {
		return this.todayOpen;
	}

	public void setTodayOpen(Long todayOpen) {
		this.todayOpen = todayOpen;
	}

	@Column(name = "TODAY_PROFIT", scale = 3)
	public BigDecimal getTodayProfit() {
		return this.todayProfit;
	}

	public void setTodayProfit(BigDecimal todayProfit) {
		this.todayProfit = todayProfit;
	}

	@Column(name = "TOTAL_PROFIT", scale = 3)
	public BigDecimal getTotalProfit() {
		return this.totalProfit;
	}

	public void setTotalProfit(BigDecimal totalProfit) {
		this.totalProfit = totalProfit;
	}

}
