package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * THisTrade generated by hbm2java
 */
@Entity
@Table(name = "T_HIS_TRADE")
public class THisTrade implements java.io.Serializable {

	private THisTradeId id;
	private String orderId;
	private String memberId;
	private String accountId;
	private String exchClientId;
	private String userId;
	private String portfolioId;
	private String tradeType;
	private String instrumentId;
	private String offsetFlag;
	private String hedgeFlag;
	private BigDecimal price;
	private BigDecimal priceEx;
	private Long volume;
	private String tradeTime;
	private String localOrderId;
	private BigDecimal usedFee;
	private BigDecimal usedMargin;
	private BigDecimal premium;
	private BigDecimal closeProfit;
	private String orderUserId;

	public THisTrade() {
	}

	public THisTrade(THisTradeId id, String accountId, String portfolioId) {
		this.id = id;
		this.accountId = accountId;
		this.portfolioId = portfolioId;
	}

	public THisTrade(THisTradeId id, String orderId, String memberId, String accountId, String exchClientId,
			String userId, String portfolioId, String tradeType, String instrumentId, String offsetFlag,
			String hedgeFlag, BigDecimal price, BigDecimal priceEx, Long volume, String tradeTime, String localOrderId,
			BigDecimal usedFee, BigDecimal usedMargin, BigDecimal premium, BigDecimal closeProfit, String orderUserId) {
		this.id = id;
		this.orderId = orderId;
		this.memberId = memberId;
		this.accountId = accountId;
		this.exchClientId = exchClientId;
		this.userId = userId;
		this.portfolioId = portfolioId;
		this.tradeType = tradeType;
		this.instrumentId = instrumentId;
		this.offsetFlag = offsetFlag;
		this.hedgeFlag = hedgeFlag;
		this.price = price;
		this.priceEx = priceEx;
		this.volume = volume;
		this.tradeTime = tradeTime;
		this.localOrderId = localOrderId;
		this.usedFee = usedFee;
		this.usedMargin = usedMargin;
		this.premium = premium;
		this.closeProfit = closeProfit;
		this.orderUserId = orderUserId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "direction", column = @Column(name = "DIRECTION", nullable = false, length = 1)),
			@AttributeOverride(name = "tradingDay", column = @Column(name = "TRADING_DAY", nullable = false, length = 8)),
			@AttributeOverride(name = "tradeId", column = @Column(name = "TRADE_ID", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "exchId", column = @Column(name = "EXCH_ID", nullable = false, length = 30)) })
	public THisTradeId getId() {
		return this.id;
	}

	public void setId(THisTradeId id) {
		this.id = id;
	}

	@Column(name = "ORDER_ID", length = 20)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "MEMBER_ID", length = 10)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "ACCOUNT_ID", nullable = false, length = 20)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "EXCH_CLIENT_ID", length = 12)
	public String getExchClientId() {
		return this.exchClientId;
	}

	public void setExchClientId(String exchClientId) {
		this.exchClientId = exchClientId;
	}

	@Column(name = "USER_ID", length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "PORTFOLIO_ID", nullable = false, length = 12)
	public String getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(String portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Column(name = "TRADE_TYPE", length = 1)
	public String getTradeType() {
		return this.tradeType;
	}

	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	@Column(name = "INSTRUMENT_ID", length = 50)
	public String getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	@Column(name = "OFFSET_FLAG", length = 1)
	public String getOffsetFlag() {
		return this.offsetFlag;
	}

	public void setOffsetFlag(String offsetFlag) {
		this.offsetFlag = offsetFlag;
	}

	@Column(name = "HEDGE_FLAG", length = 1)
	public String getHedgeFlag() {
		return this.hedgeFlag;
	}

	public void setHedgeFlag(String hedgeFlag) {
		this.hedgeFlag = hedgeFlag;
	}

	@Column(name = "PRICE", precision = 22, scale = 6)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "PRICE_EX", precision = 36, scale = 20)
	public BigDecimal getPriceEx() {
		return this.priceEx;
	}

	public void setPriceEx(BigDecimal priceEx) {
		this.priceEx = priceEx;
	}

	@Column(name = "VOLUME", precision = 13, scale = 0)
	public Long getVolume() {
		return this.volume;
	}

	public void setVolume(Long volume) {
		this.volume = volume;
	}

	@Column(name = "TRADE_TIME", length = 8)
	public String getTradeTime() {
		return this.tradeTime;
	}

	public void setTradeTime(String tradeTime) {
		this.tradeTime = tradeTime;
	}

	@Column(name = "LOCAL_ORDER_ID", length = 20)
	public String getLocalOrderId() {
		return this.localOrderId;
	}

	public void setLocalOrderId(String localOrderId) {
		this.localOrderId = localOrderId;
	}

	@Column(name = "USED_FEE", scale = 3)
	public BigDecimal getUsedFee() {
		return this.usedFee;
	}

	public void setUsedFee(BigDecimal usedFee) {
		this.usedFee = usedFee;
	}

	@Column(name = "USED_MARGIN", scale = 3)
	public BigDecimal getUsedMargin() {
		return this.usedMargin;
	}

	public void setUsedMargin(BigDecimal usedMargin) {
		this.usedMargin = usedMargin;
	}

	@Column(name = "PREMIUM", scale = 3)
	public BigDecimal getPremium() {
		return this.premium;
	}

	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}

	@Column(name = "CLOSE_PROFIT", scale = 3)
	public BigDecimal getCloseProfit() {
		return this.closeProfit;
	}

	public void setCloseProfit(BigDecimal closeProfit) {
		this.closeProfit = closeProfit;
	}

	@Column(name = "ORDER_USER_ID", length = 20)
	public String getOrderUserId() {
		return this.orderUserId;
	}

	public void setOrderUserId(String orderUserId) {
		this.orderUserId = orderUserId;
	}

}
