package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * THisFundBalanceId generated by hbm2java
 */
@Embeddable
public class THisFundBalanceId implements java.io.Serializable {

	private String tradingDay;
	private String accountId;

	public THisFundBalanceId() {
	}

	public THisFundBalanceId(String tradingDay, String accountId) {
		this.tradingDay = tradingDay;
		this.accountId = accountId;
	}

	@Column(name = "TRADING_DAY", nullable = false, length = 8)
	public String getTradingDay() {
		return this.tradingDay;
	}

	public void setTradingDay(String tradingDay) {
		this.tradingDay = tradingDay;
	}

	@Column(name = "ACCOUNT_ID", nullable = false, length = 20)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof THisFundBalanceId))
			return false;
		THisFundBalanceId castOther = (THisFundBalanceId) other;

		return ((this.getTradingDay() == castOther.getTradingDay()) || (this.getTradingDay() != null
				&& castOther.getTradingDay() != null && this.getTradingDay().equals(castOther.getTradingDay())))
				&& ((this.getAccountId() == castOther.getAccountId()) || (this.getAccountId() != null
						&& castOther.getAccountId() != null && this.getAccountId().equals(castOther.getAccountId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradingDay() == null ? 0 : this.getTradingDay().hashCode());
		result = 37 * result + (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		return result;
	}

}
