package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * THisTradeId generated by hbm2java
 */
@Embeddable
public class THisTradeId implements java.io.Serializable {

	private String direction;
	private String tradingDay;
	private long tradeId;
	private String exchId;

	public THisTradeId() {
	}

	public THisTradeId(String direction, String tradingDay, long tradeId, String exchId) {
		this.direction = direction;
		this.tradingDay = tradingDay;
		this.tradeId = tradeId;
		this.exchId = exchId;
	}

	@Column(name = "DIRECTION", nullable = false, length = 1)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "TRADING_DAY", nullable = false, length = 8)
	public String getTradingDay() {
		return this.tradingDay;
	}

	public void setTradingDay(String tradingDay) {
		this.tradingDay = tradingDay;
	}

	@Column(name = "TRADE_ID", nullable = false, precision = 12, scale = 0)
	public long getTradeId() {
		return this.tradeId;
	}

	public void setTradeId(long tradeId) {
		this.tradeId = tradeId;
	}

	@Column(name = "EXCH_ID", nullable = false, length = 30)
	public String getExchId() {
		return this.exchId;
	}

	public void setExchId(String exchId) {
		this.exchId = exchId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof THisTradeId))
			return false;
		THisTradeId castOther = (THisTradeId) other;

		return ((this.getDirection() == castOther.getDirection()) || (this.getDirection() != null
				&& castOther.getDirection() != null && this.getDirection().equals(castOther.getDirection())))
				&& ((this.getTradingDay() == castOther.getTradingDay()) || (this.getTradingDay() != null
						&& castOther.getTradingDay() != null && this.getTradingDay().equals(castOther.getTradingDay())))
				&& (this.getTradeId() == castOther.getTradeId())
				&& ((this.getExchId() == castOther.getExchId()) || (this.getExchId() != null
						&& castOther.getExchId() != null && this.getExchId().equals(castOther.getExchId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDirection() == null ? 0 : this.getDirection().hashCode());
		result = 37 * result + (getTradingDay() == null ? 0 : this.getTradingDay().hashCode());
		result = 37 * result + (int) this.getTradeId();
		result = 37 * result + (getExchId() == null ? 0 : this.getExchId().hashCode());
		return result;
	}

}
