package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * THisOrder generated by hbm2java
 */
@Entity
@Table(name = "T_HIS_ORDER")
public class THisOrder implements java.io.Serializable {

	private THisOrderId id;
	private String memberId;
	private String accountId;
	private String portfolioId;
	private String exchClientId;
	private String tradeType;
	private String instrumentId;
	private String direction;
	private String offsetFlag;
	private String hedgeFlag;
	private String orderPriceType;
	private BigDecimal limitPrice;
	private Long volume;
	private String timeCondition;
	private String gtdDate;
	private String volumeCondition;
	private Long minVolume;
	private BigDecimal stopPrice;
	private String forceCloseReason;
	private String isAutoSuspend;
	private String orderSource;
	private String insertTime;
	private String localOrderId;
	private String bizUnit;
	private String cancelTime;
	private String cancelUserId;
	private Long volumeTraded;
	private BigDecimal frozenPermium;
	private BigDecimal frozenMargin;
	private BigDecimal frozenFee;
	private String orderStatus;
	private String isAuto;
	private String userId;
	private String userCustom;
	private String orderUserId;
	private String orderBatch;
	private String seatId;
	private String exchLocalOrderId;
	private String errCode;
	private String errMsg;

	public THisOrder() {
	}

	public THisOrder(THisOrderId id, String accountId, String portfolioId, String direction) {
		this.id = id;
		this.accountId = accountId;
		this.portfolioId = portfolioId;
		this.direction = direction;
	}

	public THisOrder(THisOrderId id, String memberId, String accountId, String portfolioId, String exchClientId,
			String tradeType, String instrumentId, String direction, String offsetFlag, String hedgeFlag,
			String orderPriceType, BigDecimal limitPrice, Long volume, String timeCondition, String gtdDate,
			String volumeCondition, Long minVolume, BigDecimal stopPrice, String forceCloseReason, String isAutoSuspend,
			String orderSource, String insertTime, String localOrderId, String bizUnit, String cancelTime,
			String cancelUserId, Long volumeTraded, BigDecimal frozenPermium, BigDecimal frozenMargin,
			BigDecimal frozenFee, String orderStatus, String isAuto, String userId, String userCustom,
			String orderUserId, String orderBatch, String seatId, String exchLocalOrderId, String errCode,
			String errMsg) {
		this.id = id;
		this.memberId = memberId;
		this.accountId = accountId;
		this.portfolioId = portfolioId;
		this.exchClientId = exchClientId;
		this.tradeType = tradeType;
		this.instrumentId = instrumentId;
		this.direction = direction;
		this.offsetFlag = offsetFlag;
		this.hedgeFlag = hedgeFlag;
		this.orderPriceType = orderPriceType;
		this.limitPrice = limitPrice;
		this.volume = volume;
		this.timeCondition = timeCondition;
		this.gtdDate = gtdDate;
		this.volumeCondition = volumeCondition;
		this.minVolume = minVolume;
		this.stopPrice = stopPrice;
		this.forceCloseReason = forceCloseReason;
		this.isAutoSuspend = isAutoSuspend;
		this.orderSource = orderSource;
		this.insertTime = insertTime;
		this.localOrderId = localOrderId;
		this.bizUnit = bizUnit;
		this.cancelTime = cancelTime;
		this.cancelUserId = cancelUserId;
		this.volumeTraded = volumeTraded;
		this.frozenPermium = frozenPermium;
		this.frozenMargin = frozenMargin;
		this.frozenFee = frozenFee;
		this.orderStatus = orderStatus;
		this.isAuto = isAuto;
		this.userId = userId;
		this.userCustom = userCustom;
		this.orderUserId = orderUserId;
		this.orderBatch = orderBatch;
		this.seatId = seatId;
		this.exchLocalOrderId = exchLocalOrderId;
		this.errCode = errCode;
		this.errMsg = errMsg;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tradingDay", column = @Column(name = "TRADING_DAY", nullable = false, length = 8)),
			@AttributeOverride(name = "exchId", column = @Column(name = "EXCH_ID", nullable = false, length = 30)),
			@AttributeOverride(name = "orderId", column = @Column(name = "ORDER_ID", nullable = false, length = 20)) })
	public THisOrderId getId() {
		return this.id;
	}

	public void setId(THisOrderId id) {
		this.id = id;
	}

	@Column(name = "MEMBER_ID", length = 10)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "ACCOUNT_ID", nullable = false, length = 20)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "PORTFOLIO_ID", nullable = false, length = 12)
	public String getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(String portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Column(name = "EXCH_CLIENT_ID", length = 12)
	public String getExchClientId() {
		return this.exchClientId;
	}

	public void setExchClientId(String exchClientId) {
		this.exchClientId = exchClientId;
	}

	@Column(name = "TRADE_TYPE", length = 1)
	public String getTradeType() {
		return this.tradeType;
	}

	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	@Column(name = "INSTRUMENT_ID", length = 50)
	public String getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	@Column(name = "DIRECTION", nullable = false, length = 1)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "OFFSET_FLAG", length = 1)
	public String getOffsetFlag() {
		return this.offsetFlag;
	}

	public void setOffsetFlag(String offsetFlag) {
		this.offsetFlag = offsetFlag;
	}

	@Column(name = "HEDGE_FLAG", length = 1)
	public String getHedgeFlag() {
		return this.hedgeFlag;
	}

	public void setHedgeFlag(String hedgeFlag) {
		this.hedgeFlag = hedgeFlag;
	}

	@Column(name = "ORDER_PRICE_TYPE", length = 1)
	public String getOrderPriceType() {
		return this.orderPriceType;
	}

	public void setOrderPriceType(String orderPriceType) {
		this.orderPriceType = orderPriceType;
	}

	@Column(name = "LIMIT_PRICE", precision = 22, scale = 6)
	public BigDecimal getLimitPrice() {
		return this.limitPrice;
	}

	public void setLimitPrice(BigDecimal limitPrice) {
		this.limitPrice = limitPrice;
	}

	@Column(name = "VOLUME", precision = 13, scale = 0)
	public Long getVolume() {
		return this.volume;
	}

	public void setVolume(Long volume) {
		this.volume = volume;
	}

	@Column(name = "TIME_CONDITION", length = 1)
	public String getTimeCondition() {
		return this.timeCondition;
	}

	public void setTimeCondition(String timeCondition) {
		this.timeCondition = timeCondition;
	}

	@Column(name = "GTD_DATE", length = 8)
	public String getGtdDate() {
		return this.gtdDate;
	}

	public void setGtdDate(String gtdDate) {
		this.gtdDate = gtdDate;
	}

	@Column(name = "VOLUME_CONDITION", length = 1)
	public String getVolumeCondition() {
		return this.volumeCondition;
	}

	public void setVolumeCondition(String volumeCondition) {
		this.volumeCondition = volumeCondition;
	}

	@Column(name = "MIN_VOLUME", precision = 13, scale = 0)
	public Long getMinVolume() {
		return this.minVolume;
	}

	public void setMinVolume(Long minVolume) {
		this.minVolume = minVolume;
	}

	@Column(name = "STOP_PRICE", precision = 22, scale = 6)
	public BigDecimal getStopPrice() {
		return this.stopPrice;
	}

	public void setStopPrice(BigDecimal stopPrice) {
		this.stopPrice = stopPrice;
	}

	@Column(name = "FORCE_CLOSE_REASON", length = 1)
	public String getForceCloseReason() {
		return this.forceCloseReason;
	}

	public void setForceCloseReason(String forceCloseReason) {
		this.forceCloseReason = forceCloseReason;
	}

	@Column(name = "IS_AUTO_SUSPEND", length = 1)
	public String getIsAutoSuspend() {
		return this.isAutoSuspend;
	}

	public void setIsAutoSuspend(String isAutoSuspend) {
		this.isAutoSuspend = isAutoSuspend;
	}

	@Column(name = "ORDER_SOURCE", length = 1)
	public String getOrderSource() {
		return this.orderSource;
	}

	public void setOrderSource(String orderSource) {
		this.orderSource = orderSource;
	}

	@Column(name = "INSERT_TIME", length = 8)
	public String getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(String insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "LOCAL_ORDER_ID", length = 20)
	public String getLocalOrderId() {
		return this.localOrderId;
	}

	public void setLocalOrderId(String localOrderId) {
		this.localOrderId = localOrderId;
	}

	@Column(name = "BIZ_UNIT", length = 250)
	public String getBizUnit() {
		return this.bizUnit;
	}

	public void setBizUnit(String bizUnit) {
		this.bizUnit = bizUnit;
	}

	@Column(name = "CANCEL_TIME", length = 8)
	public String getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(String cancelTime) {
		this.cancelTime = cancelTime;
	}

	@Column(name = "CANCEL_USER_ID", length = 20)
	public String getCancelUserId() {
		return this.cancelUserId;
	}

	public void setCancelUserId(String cancelUserId) {
		this.cancelUserId = cancelUserId;
	}

	@Column(name = "VOLUME_TRADED", precision = 13, scale = 0)
	public Long getVolumeTraded() {
		return this.volumeTraded;
	}

	public void setVolumeTraded(Long volumeTraded) {
		this.volumeTraded = volumeTraded;
	}

	@Column(name = "FROZEN_PERMIUM", scale = 3)
	public BigDecimal getFrozenPermium() {
		return this.frozenPermium;
	}

	public void setFrozenPermium(BigDecimal frozenPermium) {
		this.frozenPermium = frozenPermium;
	}

	@Column(name = "FROZEN_MARGIN", scale = 3)
	public BigDecimal getFrozenMargin() {
		return this.frozenMargin;
	}

	public void setFrozenMargin(BigDecimal frozenMargin) {
		this.frozenMargin = frozenMargin;
	}

	@Column(name = "FROZEN_FEE", scale = 3)
	public BigDecimal getFrozenFee() {
		return this.frozenFee;
	}

	public void setFrozenFee(BigDecimal frozenFee) {
		this.frozenFee = frozenFee;
	}

	@Column(name = "ORDER_STATUS", length = 1)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "IS_AUTO", length = 1)
	public String getIsAuto() {
		return this.isAuto;
	}

	public void setIsAuto(String isAuto) {
		this.isAuto = isAuto;
	}

	@Column(name = "USER_ID", length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_CUSTOM", length = 50)
	public String getUserCustom() {
		return this.userCustom;
	}

	public void setUserCustom(String userCustom) {
		this.userCustom = userCustom;
	}

	@Column(name = "ORDER_USER_ID", length = 20)
	public String getOrderUserId() {
		return this.orderUserId;
	}

	public void setOrderUserId(String orderUserId) {
		this.orderUserId = orderUserId;
	}

	@Column(name = "ORDER_BATCH", length = 50)
	public String getOrderBatch() {
		return this.orderBatch;
	}

	public void setOrderBatch(String orderBatch) {
		this.orderBatch = orderBatch;
	}

	@Column(name = "SEAT_ID", length = 50)
	public String getSeatId() {
		return this.seatId;
	}

	public void setSeatId(String seatId) {
		this.seatId = seatId;
	}

	@Column(name = "EXCH_LOCAL_ORDER_ID", length = 50)
	public String getExchLocalOrderId() {
		return this.exchLocalOrderId;
	}

	public void setExchLocalOrderId(String exchLocalOrderId) {
		this.exchLocalOrderId = exchLocalOrderId;
	}

	@Column(name = "ERR_CODE", length = 50)
	public String getErrCode() {
		return this.errCode;
	}

	public void setErrCode(String errCode) {
		this.errCode = errCode;
	}

	@Column(name = "ERR_MSG")
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

}
