package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * THisPortfolioPositionId generated by hbm2java
 */
@Embeddable
public class THisPortfolioPositionId implements java.io.Serializable {

	private String tradingDay;
	private String portfolioId;
	private String instrumentId;
	private String hedgeFlag;
	private String direction;

	public THisPortfolioPositionId() {
	}

	public THisPortfolioPositionId(String tradingDay, String portfolioId, String instrumentId, String hedgeFlag,
			String direction) {
		this.tradingDay = tradingDay;
		this.portfolioId = portfolioId;
		this.instrumentId = instrumentId;
		this.hedgeFlag = hedgeFlag;
		this.direction = direction;
	}

	@Column(name = "TRADING_DAY", nullable = false, length = 8)
	public String getTradingDay() {
		return this.tradingDay;
	}

	public void setTradingDay(String tradingDay) {
		this.tradingDay = tradingDay;
	}

	@Column(name = "PORTFOLIO_ID", nullable = false, length = 12)
	public String getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(String portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Column(name = "INSTRUMENT_ID", nullable = false, length = 50)
	public String getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	@Column(name = "HEDGE_FLAG", nullable = false, length = 1)
	public String getHedgeFlag() {
		return this.hedgeFlag;
	}

	public void setHedgeFlag(String hedgeFlag) {
		this.hedgeFlag = hedgeFlag;
	}

	@Column(name = "DIRECTION", nullable = false, length = 50)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof THisPortfolioPositionId))
			return false;
		THisPortfolioPositionId castOther = (THisPortfolioPositionId) other;

		return ((this.getTradingDay() == castOther.getTradingDay()) || (this.getTradingDay() != null
				&& castOther.getTradingDay() != null && this.getTradingDay().equals(castOther.getTradingDay())))
				&& ((this.getPortfolioId() == castOther.getPortfolioId())
						|| (this.getPortfolioId() != null && castOther.getPortfolioId() != null
								&& this.getPortfolioId().equals(castOther.getPortfolioId())))
				&& ((this.getInstrumentId() == castOther.getInstrumentId())
						|| (this.getInstrumentId() != null && castOther.getInstrumentId() != null
								&& this.getInstrumentId().equals(castOther.getInstrumentId())))
				&& ((this.getHedgeFlag() == castOther.getHedgeFlag()) || (this.getHedgeFlag() != null
						&& castOther.getHedgeFlag() != null && this.getHedgeFlag().equals(castOther.getHedgeFlag())))
				&& ((this.getDirection() == castOther.getDirection()) || (this.getDirection() != null
						&& castOther.getDirection() != null && this.getDirection().equals(castOther.getDirection())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradingDay() == null ? 0 : this.getTradingDay().hashCode());
		result = 37 * result + (getPortfolioId() == null ? 0 : this.getPortfolioId().hashCode());
		result = 37 * result + (getInstrumentId() == null ? 0 : this.getInstrumentId().hashCode());
		result = 37 * result + (getHedgeFlag() == null ? 0 : this.getHedgeFlag().hashCode());
		result = 37 * result + (getDirection() == null ? 0 : this.getDirection().hashCode());
		return result;
	}

}
