package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TInstrumentMarginId generated by hbm2java
 */
@Embeddable
public class TInstrumentMarginId implements java.io.Serializable {

	private String instrumentId;
	private String codeType;
	private String hedgeFlag;

	public TInstrumentMarginId() {
	}

	public TInstrumentMarginId(String instrumentId, String codeType, String hedgeFlag) {
		this.instrumentId = instrumentId;
		this.codeType = codeType;
		this.hedgeFlag = hedgeFlag;
	}

	@Column(name = "INSTRUMENT_ID", nullable = false, length = 50)
	public String getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	@Column(name = "CODE_TYPE", nullable = false, length = 1)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "HEDGE_FLAG", nullable = false, length = 1)
	public String getHedgeFlag() {
		return this.hedgeFlag;
	}

	public void setHedgeFlag(String hedgeFlag) {
		this.hedgeFlag = hedgeFlag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TInstrumentMarginId))
			return false;
		TInstrumentMarginId castOther = (TInstrumentMarginId) other;

		return ((this.getInstrumentId() == castOther.getInstrumentId()) || (this.getInstrumentId() != null
				&& castOther.getInstrumentId() != null && this.getInstrumentId().equals(castOther.getInstrumentId())))
				&& ((this.getCodeType() == castOther.getCodeType()) || (this.getCodeType() != null
						&& castOther.getCodeType() != null && this.getCodeType().equals(castOther.getCodeType())))
				&& ((this.getHedgeFlag() == castOther.getHedgeFlag()) || (this.getHedgeFlag() != null
						&& castOther.getHedgeFlag() != null && this.getHedgeFlag().equals(castOther.getHedgeFlag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getInstrumentId() == null ? 0 : this.getInstrumentId().hashCode());
		result = 37 * result + (getCodeType() == null ? 0 : this.getCodeType().hashCode());
		result = 37 * result + (getHedgeFlag() == null ? 0 : this.getHedgeFlag().hashCode());
		return result;
	}

}
