package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TInstrumentPriceId generated by hbm2java
 */
@Embeddable
public class TInstrumentPriceId implements java.io.Serializable {

	private String tradingDay;
	private String instrumentId;

	public TInstrumentPriceId() {
	}

	public TInstrumentPriceId(String tradingDay, String instrumentId) {
		this.tradingDay = tradingDay;
		this.instrumentId = instrumentId;
	}

	@Column(name = "TRADING_DAY", nullable = false, length = 8)
	public String getTradingDay() {
		return this.tradingDay;
	}

	public void setTradingDay(String tradingDay) {
		this.tradingDay = tradingDay;
	}

	@Column(name = "INSTRUMENT_ID", nullable = false, length = 50)
	public String getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(String instrumentId) {
		this.instrumentId = instrumentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TInstrumentPriceId))
			return false;
		TInstrumentPriceId castOther = (TInstrumentPriceId) other;

		return ((this.getTradingDay() == castOther.getTradingDay()) || (this.getTradingDay() != null
				&& castOther.getTradingDay() != null && this.getTradingDay().equals(castOther.getTradingDay())))
				&& ((this.getInstrumentId() == castOther.getInstrumentId())
						|| (this.getInstrumentId() != null && castOther.getInstrumentId() != null
								&& this.getInstrumentId().equals(castOther.getInstrumentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTradingDay() == null ? 0 : this.getTradingDay().hashCode());
		result = 37 * result + (getInstrumentId() == null ? 0 : this.getInstrumentId().hashCode());
		return result;
	}

}
