package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TInstrumentPrice generated by hbm2java
 */
@Entity
@Table(name = "T_INSTRUMENT_PRICE")
public class TInstrumentPrice implements java.io.Serializable {

	private TInstrumentPriceId id;
	private BigDecimal settlementPrice;
	private BigDecimal closePrice;

	public TInstrumentPrice() {
	}

	public TInstrumentPrice(TInstrumentPriceId id) {
		this.id = id;
	}

	public TInstrumentPrice(TInstrumentPriceId id, BigDecimal settlementPrice, BigDecimal closePrice) {
		this.id = id;
		this.settlementPrice = settlementPrice;
		this.closePrice = closePrice;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tradingDay", column = @Column(name = "TRADING_DAY", nullable = false, length = 8)),
			@AttributeOverride(name = "instrumentId", column = @Column(name = "INSTRUMENT_ID", nullable = false, length = 50)) })
	public TInstrumentPriceId getId() {
		return this.id;
	}

	public void setId(TInstrumentPriceId id) {
		this.id = id;
	}

	@Column(name = "SETTLEMENT_PRICE", precision = 22, scale = 6)
	public BigDecimal getSettlementPrice() {
		return this.settlementPrice;
	}

	public void setSettlementPrice(BigDecimal settlementPrice) {
		this.settlementPrice = settlementPrice;
	}

	@Column(name = "CLOSE_PRICE", precision = 22, scale = 6)
	public BigDecimal getClosePrice() {
		return this.closePrice;
	}

	public void setClosePrice(BigDecimal closePrice) {
		this.closePrice = closePrice;
	}

}
