package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TInstrumentFee generated by hbm2java
 */
@Entity
@Table(name = "T_INSTRUMENT_FEE")
public class TInstrumentFee implements java.io.Serializable {

	private TInstrumentFeeId id;
	private BigDecimal openFeeRate;
	private BigDecimal closeTodayFeeRate;
	private BigDecimal closeFeeRate;
	private String remark;
	private String operDate;
	private String operTime;
	private String operId;

	public TInstrumentFee() {
	}

	public TInstrumentFee(TInstrumentFeeId id) {
		this.id = id;
	}

	public TInstrumentFee(TInstrumentFeeId id, BigDecimal openFeeRate, BigDecimal closeTodayFeeRate,
			BigDecimal closeFeeRate, String remark, String operDate, String operTime, String operId) {
		this.id = id;
		this.openFeeRate = openFeeRate;
		this.closeTodayFeeRate = closeTodayFeeRate;
		this.closeFeeRate = closeFeeRate;
		this.remark = remark;
		this.operDate = operDate;
		this.operTime = operTime;
		this.operId = operId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "instrumentId", column = @Column(name = "INSTRUMENT_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "codeType", column = @Column(name = "CODE_TYPE", nullable = false, length = 1)),
			@AttributeOverride(name = "hedgeFlag", column = @Column(name = "HEDGE_FLAG", nullable = false, length = 1)) })
	public TInstrumentFeeId getId() {
		return this.id;
	}

	public void setId(TInstrumentFeeId id) {
		this.id = id;
	}

	@Column(name = "OPEN_FEE_RATE", scale = 6)
	public BigDecimal getOpenFeeRate() {
		return this.openFeeRate;
	}

	public void setOpenFeeRate(BigDecimal openFeeRate) {
		this.openFeeRate = openFeeRate;
	}

	@Column(name = "CLOSE_TODAY_FEE_RATE", scale = 6)
	public BigDecimal getCloseTodayFeeRate() {
		return this.closeTodayFeeRate;
	}

	public void setCloseTodayFeeRate(BigDecimal closeTodayFeeRate) {
		this.closeTodayFeeRate = closeTodayFeeRate;
	}

	@Column(name = "CLOSE_FEE_RATE", scale = 6)
	public BigDecimal getCloseFeeRate() {
		return this.closeFeeRate;
	}

	public void setCloseFeeRate(BigDecimal closeFeeRate) {
		this.closeFeeRate = closeFeeRate;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "OPER_DATE", length = 8)
	public String getOperDate() {
		return this.operDate;
	}

	public void setOperDate(String operDate) {
		this.operDate = operDate;
	}

	@Column(name = "OPER_TIME", length = 8)
	public String getOperTime() {
		return this.operTime;
	}

	public void setOperTime(String operTime) {
		this.operTime = operTime;
	}

	@Column(name = "OPER_ID", length = 20)
	public String getOperId() {
		return this.operId;
	}

	public void setOperId(String operId) {
		this.operId = operId;
	}

}
