package com.cffex.mts_settle;
// Generated 2016-10-19 17:50:46 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUnderlyingMarket generated by hbm2java
 */
@Entity
@Table(name = "T_UNDERLYING_MARKET")
public class TUnderlyingMarket implements java.io.Serializable {

	private String tradingDay;
	private String productId;
	private String productName;
	private String underlyingId;
	private String underlyingName;
	private String exchId;
	private BigDecimal settlementPrice;
	private BigDecimal closedPrice;

	public TUnderlyingMarket() {
	}

	public TUnderlyingMarket(String tradingDay, String productId, String productName, String underlyingId,
			String underlyingName, String exchId) {
		this.tradingDay = tradingDay;
		this.productId = productId;
		this.productName = productName;
		this.underlyingId = underlyingId;
		this.underlyingName = underlyingName;
		this.exchId = exchId;
	}

	public TUnderlyingMarket(String tradingDay, String productId, String productName, String underlyingId,
			String underlyingName, String exchId, BigDecimal settlementPrice, BigDecimal closedPrice) {
		this.tradingDay = tradingDay;
		this.productId = productId;
		this.productName = productName;
		this.underlyingId = underlyingId;
		this.underlyingName = underlyingName;
		this.exchId = exchId;
		this.settlementPrice = settlementPrice;
		this.closedPrice = closedPrice;
	}

	@Id

	@Column(name = "TRADING_DAY", unique = true, nullable = false, length = 8)
	public String getTradingDay() {
		return this.tradingDay;
	}

	public void setTradingDay(String tradingDay) {
		this.tradingDay = tradingDay;
	}

	@Column(name = "PRODUCT_ID", nullable = false, length = 30)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "PRODUCT_NAME", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "UNDERLYING_ID", nullable = false, length = 30)
	public String getUnderlyingId() {
		return this.underlyingId;
	}

	public void setUnderlyingId(String underlyingId) {
		this.underlyingId = underlyingId;
	}

	@Column(name = "UNDERLYING_NAME", nullable = false, length = 100)
	public String getUnderlyingName() {
		return this.underlyingName;
	}

	public void setUnderlyingName(String underlyingName) {
		this.underlyingName = underlyingName;
	}

	@Column(name = "EXCH_ID", nullable = false, length = 30)
	public String getExchId() {
		return this.exchId;
	}

	public void setExchId(String exchId) {
		this.exchId = exchId;
	}

	@Column(name = "SETTLEMENT_PRICE", precision = 22, scale = 6)
	public BigDecimal getSettlementPrice() {
		return this.settlementPrice;
	}

	public void setSettlementPrice(BigDecimal settlementPrice) {
		this.settlementPrice = settlementPrice;
	}

	@Column(name = "CLOSED_PRICE", precision = 22, scale = 6)
	public BigDecimal getClosedPrice() {
		return this.closedPrice;
	}

	public void setClosedPrice(BigDecimal closedPrice) {
		this.closedPrice = closedPrice;
	}

}
